import React, { useEffect, useState, useRef } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import Header from "../components/Header";
import Disclaimer from "../components/Disclaimer";
import { api, API_BASE } from "../lib/api";
import { downloadStructuredExport, fileSlug } from "../lib/exportFiles";
import { toast } from "sonner";
import { ArrowLeft, Upload, File, Trash2, Send, Settings, FileText, Scale, Search, ExternalLink, Sparkles, GitCompareArrows, BookOpen, Download, Archive } from "lucide-react";
import CameraCapture from "../components/CameraCapture";

const CORE_TABS = [
  { id: "playground", label: "Playground", icon: Send },
  { id: "config", label: "Configuration", icon: Settings },
];

const FEATURE_TABS = [
  { id: "documents", label: "Documents", icon: FileText, modules: ["rag", "camera"] },
  { id: "caselaw", label: "Case Law", icon: Scale, modules: ["caselaw"] },
  { id: "compare", label: "Compare", icon: GitCompareArrows, modules: ["compare"] },
  { id: "reader", label: "Guided Reader", icon: BookOpen, modules: ["guided_reader"] },
  { id: "brief_export", label: "Bundles", icon: Archive, modules: ["brief_export"] },
];

function tabsForApp(app) {
  const modules = Array.isArray(app?.modules) ? app.modules : [];
  const legacyApp = modules.length === 0;
  const enabledFeatures = FEATURE_TABS.filter((tab) => legacyApp || tab.modules.some((module) => modules.includes(module)));
  return [CORE_TABS[0], ...enabledFeatures, CORE_TABS[1]];
}

function renderCitations(text) {
  // Replace [S1] etc with clickable citation badges
  const parts = text.split(/(\[S\d+\])/g);
  return parts.map((p, i) => {
    if (/^\[S\d+\]$/.test(p)) {
      return <span key={i} className="citation-badge" data-testid={`citation-${p}`}>{p}</span>;
    }
    return <span key={i}>{p}</span>;
  });
}

function mergeCitations(existing = [], incoming = []) {
  const merged = new Map();
  [...existing, ...incoming].filter(Boolean).forEach((citation) => {
    merged.set(citation.tag || citation.chunk_id || JSON.stringify(citation), citation);
  });
  return Array.from(merged.values());
}

function parseSseBlock(raw) {
  const lines = String(raw || "").split(/\r?\n/);
  const event = lines.find((line) => line.startsWith("event:"))?.slice(6).trim() || "message";
  const dataText = lines
    .filter((line) => line.startsWith("data:"))
    .map((line) => line.slice(5).trimStart())
    .join("\n");
  if (!dataText) return { event, data: null };
  return { event, data: JSON.parse(dataText) };
}

const EXPORT_FORMATS = [
  { id: "word", label: "Word", extension: ".doc" },
  { id: "pdf", label: "PDF", extension: ".pdf" },
  { id: "ppt", label: "PowerPoint", extension: ".ppt" },
];

function citationSources(run) {
  return (run?.citations || []).map((citation) => {
    const ord = Number(citation.ord);
    return {
      tag: citation.tag,
      title: citation.doc_name || citation.title || "Citation source",
      status: citation.chunk_id ? `Chunk ${Number.isFinite(ord) ? ord + 1 : citation.chunk_id}` : "Citation",
      score: citation.score,
      preview: citation.preview || "",
    };
  });
}

function documentSources(documents = [], includePreviews = true) {
  return documents.map((doc, index) => ({
    tag: `D${index + 1}`,
    title: doc.filename || doc.original_filename || `Document ${index + 1}`,
    status: [
      doc.text_extraction_status || "UNKNOWN",
      doc.chunk_count !== undefined ? `${doc.chunk_count} chunks` : "",
      doc.indexed_char_count ? `${doc.indexed_char_count} indexed chars` : "",
    ].filter(Boolean).join(" / "),
    preview: includePreviews ? (doc.text_preview || doc.text_extraction_message || "") : (doc.text_extraction_message || ""),
    chunk_count: doc.chunk_count,
  }));
}

function selectedAnswerExportPayload(app, run, documents = []) {
  const sources = citationSources(run);
  const fallbackSources = sources.length ? sources : documentSources(documents, false);
  return {
    title: `${app?.name || "ADA Studio"} - Selected Answer`,
    subtitle: run?.question || "Exported app answer",
    metadata: {
      App: app?.name || "Unknown app",
      Jurisdiction: app?.jurisdiction || "United Kingdom",
      Model: run?.model || app?.model || "unknown",
      Scope: "Selected answer",
      Generated: new Date().toLocaleString(),
      Citations: sources.length,
      Sources: fallbackSources.length,
    },
    sections: [
      { title: "Question", body: run?.question || "" },
      { title: "Answer", body: run?.answer || "" },
    ],
    sources: fallbackSources,
    footerNote: "Generated by ADA Studio. Preserve source verification and legal review before relying on this output.",
  };
}

function matterBundleExportPayload(app, bundleData, currentRun, includeAnswer = true) {
  const documents = bundleData?.documents || [];
  const sections = [
    {
      title: "Matter Overview",
      body: [
        `App: ${app?.name || bundleData?.app?.name || "Unknown app"}`,
        `Jurisdiction: ${app?.jurisdiction || bundleData?.app?.jurisdiction || "United Kingdom"}`,
        `Documents: ${documents.length}`,
        `Generated: ${new Date(bundleData?.generated_at || Date.now()).toLocaleString()}`,
      ].join("\n"),
    },
    {
      title: "Document Inventory",
      body: documents.length
        ? documents.map((doc, index) => `${index + 1}. ${doc.filename} - ${doc.text_extraction_status || "UNKNOWN"} - ${doc.chunk_count || 0} chunks`).join("\n")
        : "No documents are currently attached to this app.",
    },
  ];
  if (includeAnswer && currentRun?.answer) {
    sections.push(
      { title: "Selected Answer", body: `Question: ${currentRun.question}\n\n${currentRun.answer}` },
      { title: "Answer Citations", body: (currentRun.citations || []).map((citation) => `[${citation.tag}] ${citation.doc_name}\n${citation.preview}`).join("\n\n") || "No citations were attached to the selected answer." },
    );
  }
  sections.push({
    title: "Source Extract Appendix",
    body: documents.map((doc) => [
      `## ${doc.filename}`,
      `Status: ${doc.text_extraction_status || "UNKNOWN"}`,
      doc.index_truncated ? "Note: Indexed preview was truncated for Worker limits." : "",
      doc.text_preview || doc.text_extraction_message || "No text preview available.",
    ].filter(Boolean).join("\n")).join("\n\n"),
  });
  return {
    title: `${app?.name || bundleData?.app?.name || "ADA Studio"} - Matter Bundle`,
    subtitle: "Full app bundle with document inventory, selected answer, citations, and source appendix",
    metadata: {
      App: app?.name || bundleData?.app?.name || "Unknown app",
      Jurisdiction: app?.jurisdiction || bundleData?.app?.jurisdiction || "United Kingdom",
      Model: app?.model || bundleData?.app?.model || "unknown",
      Scope: includeAnswer && currentRun?.answer ? "Full matter bundle plus selected answer" : "Full matter bundle",
      Generated: new Date(bundleData?.generated_at || Date.now()).toLocaleString(),
      Documents: documents.length,
      Citations: currentRun?.citations?.length || 0,
    },
    sections,
    sources: [
      ...citationSources(currentRun),
      ...documentSources(documents, true),
    ],
    footerNote: "This bundle is an export of indexed app material and generated answers. Verify against the original uploaded documents before filing or sending.",
  };
}

function ExportButtonRow({ onExport, disabled = false, testPrefix }) {
  return (
    <div className="flex flex-wrap gap-2">
      {EXPORT_FORMATS.map((format) => (
        <button
          key={format.id}
          onClick={() => onExport(format.id)}
          disabled={disabled}
          className="border border-gray-300 px-3 py-2 hover:border-ink hover:bg-gray-50 text-xs inline-flex items-center gap-2 disabled:opacity-50"
          data-testid={`${testPrefix}-${format.id}`}
        >
          <Download size={13} /> {format.label}
        </button>
      ))}
    </div>
  );
}

function ToolBackedFeature({ title, description, to, icon: Icon }) {
  return (
    <div className="border border-gray-200 p-8 sm:p-10" data-testid={`feature-${to.split("tab=")[1]}`}>
      <Icon size={28} strokeWidth={1.5} className="text-klein mb-4" />
      <h2 className="font-serif text-3xl tracking-tight mb-2">{title}</h2>
      <p className="text-sm text-gray-600 max-w-2xl mb-5">{description}</p>
      <Link to={to} className="inline-flex items-center gap-2 bg-ink text-white px-5 py-2.5 hover:bg-klein transition-colors text-sm">
        Open in Studio <ExternalLink size={13} />
      </Link>
    </div>
  );
}

function BundleExportPanel({ appId, appData, docs, currentRun }) {
  const [scope, setScope] = useState("matter");
  const [includeAnswer, setIncludeAnswer] = useState(true);
  const [loading, setLoading] = useState(false);
  const hasAnswer = Boolean(currentRun?.answer);
  const citationCount = currentRun?.citations?.length || 0;

  const exportBundle = async (format) => {
    if (scope === "answer" && !hasAnswer) {
      toast.error("Run or select an answer before exporting it");
      return;
    }
    setLoading(true);
    try {
      const { data } = await api.get(`/apps/${appId}/bundle-data`);
      const payload = scope === "answer"
        ? selectedAnswerExportPayload(appData, currentRun, data.documents || docs)
        : matterBundleExportPayload(appData, data, currentRun, includeAnswer);
      downloadStructuredExport(
        payload,
        format,
        `${fileSlug(appData?.name)}-${scope === "answer" ? "selected-answer" : "matter-bundle"}`,
      );
    } catch (err) {
      toast.error(err.response?.data?.detail || "Bundle export failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="space-y-6" data-testid="bundle-export-tab">
      <div className="border-b border-gray-200 pb-5">
        <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500 mb-2">// export</div>
        <h2 className="font-serif text-3xl mb-2">Document Bundles</h2>
        <p className="text-sm text-gray-600 max-w-3xl">
          Export selected answers or a full matter bundle with cover metadata, preserved headings and citations, and a source list appendix.
        </p>
      </div>

      <div className="grid md:grid-cols-2 border border-gray-200">
        <button
          onClick={() => setScope("matter")}
          className={`p-4 text-left border-b md:border-b-0 md:border-r border-gray-200 ${scope === "matter" ? "bg-klein-bg" : "hover:bg-gray-50"}`}
          data-testid="bundle-scope-matter"
        >
          <div className="font-medium flex items-center gap-2"><Archive size={15} /> Full matter bundle</div>
          <p className="text-xs text-gray-600 mt-1">Cover page, document inventory, current answer, citations, and source appendix.</p>
        </button>
        <button
          onClick={() => setScope("answer")}
          className={`p-4 text-left ${scope === "answer" ? "bg-klein-bg" : "hover:bg-gray-50"}`}
          data-testid="bundle-scope-answer"
        >
          <div className="font-medium flex items-center gap-2"><Download size={15} /> Selected answer only</div>
          <p className="text-xs text-gray-600 mt-1">Export the latest Playground answer with its question, metadata, and cited sources.</p>
        </button>
      </div>

      {scope === "matter" && (
        <label className="inline-flex items-center gap-2 text-sm" data-testid="bundle-include-answer">
          <input
            type="checkbox"
            checked={includeAnswer}
            disabled={!hasAnswer}
            onChange={(event) => setIncludeAnswer(event.target.checked)}
            className="h-4 w-4 accent-klein"
          />
          Include current Playground answer
          {!hasAnswer && <span className="font-mono text-[10px] text-gray-500">(run an answer first)</span>}
        </label>
      )}

      <div className="grid sm:grid-cols-3 border border-gray-200 divide-y sm:divide-y-0 sm:divide-x divide-gray-200">
        <div className="p-4">
          <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500">Documents</div>
          <div className="font-serif text-3xl mt-1">{docs.length}</div>
        </div>
        <div className="p-4">
          <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500">Selected answer</div>
          <div className="font-serif text-3xl mt-1">{hasAnswer ? "Ready" : "None"}</div>
        </div>
        <div className="p-4">
          <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500">Citations</div>
          <div className="font-serif text-3xl mt-1">{citationCount}</div>
        </div>
      </div>

      <div className="border-t border-gray-200 pt-5">
        <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500 mb-3">Download</div>
        <ExportButtonRow
          onExport={exportBundle}
          disabled={loading || (scope === "answer" && !hasAnswer)}
          testPrefix="bundle-export"
        />
      </div>

      <div className="overflow-x-auto border border-gray-200">
        <table className="w-full border-collapse min-w-[580px]">
          <thead>
            <tr className="border-b border-gray-200 text-left font-mono text-[10px] uppercase tracking-widest text-gray-500">
              <th className="py-3 px-3">Source</th>
              <th className="py-3 px-3">Status</th>
              <th className="py-3 px-3">Chunks</th>
              <th className="py-3 px-3">Added</th>
            </tr>
          </thead>
          <tbody>
            {docs.length === 0 ? (
              <tr>
                <td colSpan="4" className="py-6 px-3 text-sm text-gray-500">No documents are attached yet. The matter bundle can still include app metadata and selected answers.</td>
              </tr>
            ) : docs.map((doc) => (
              <tr key={doc.doc_id} className="border-b border-gray-100 last:border-b-0">
                <td className="py-3 px-3 text-sm font-medium">{doc.filename}</td>
                <td className="py-3 px-3 font-mono text-[10px] text-gray-600">{doc.text_extraction_status || "UNKNOWN"}</td>
                <td className="py-3 px-3 font-mono text-xs text-gray-600">{doc.chunk_count || 0}</td>
                <td className="py-3 px-3 font-mono text-xs text-gray-600">{doc.created_at ? new Date(doc.created_at).toLocaleDateString() : "-"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export default function AppDetail() {
  const { appId } = useParams();
  const nav = useNavigate();
  const [appData, setAppData] = useState(null);
  const [tab, setTab] = useState("playground");
  const [docs, setDocs] = useState([]);
  const [meta, setMeta] = useState({ models: [] });

  // Playground state
  const [question, setQuestion] = useState("");
  const [running, setRunning] = useState(false);
  const [currentRun, setCurrentRun] = useState(null);
  const [streamStatus, setStreamStatus] = useState("");
  const [streamSteps, setStreamSteps] = useState([]);
  const [selectedCitation, setSelectedCitation] = useState(null);

  // Upload state
  const [uploading, setUploading] = useState(false);
  const fileInput = useRef(null);

  // Config edit state
  const [edit, setEdit] = useState(null);
  const [savingConfig, setSavingConfig] = useState(false);

  // Case law state
  const [clQuery, setClQuery] = useState("");
  const [clBusy, setClBusy] = useState(false);
  const [clResults, setClResults] = useState([]);
  const [clSearched, setClSearched] = useState(false);
  const [summarising, setSummarising] = useState(null); // index of case being summarised
  const [summary, setSummary] = useState(null); // {result, run}
  const [summaryFocus, setSummaryFocus] = useState("");

  const refresh = async () => {
    const [a, d, m] = await Promise.all([
      api.get(`/apps/${appId}`),
      api.get(`/apps/${appId}/documents`),
      api.get(`/meta/models`),
    ]);
    setAppData(a.data);
    setDocs(d.data);
    setMeta(m.data);
    setEdit({
      name: a.data.name, app_type: a.data.app_type, jurisdiction: a.data.jurisdiction,
      system_instructions: a.data.system_instructions, output_format: a.data.output_format,
      safety_rules: a.data.safety_rules || "", model: a.data.model,
    });
  };

  useEffect(() => { refresh().catch(() => toast.error("Failed to load app")); }, [appId]);

  const visibleTabs = tabsForApp(appData);
  const hasDocumentsFeature = visibleTabs.some((item) => item.id === "documents");

  useEffect(() => {
    if (appData && !visibleTabs.some((item) => item.id === tab)) {
      setTab(visibleTabs[0]?.id || "playground");
    }
  }, [appData, tab, visibleTabs]);

  const onUpload = async (file) => {
    if (!file) return;
    setUploading(true);
    try {
      const fd = new FormData();
      fd.append("file", file);
      const { data } = await api.post(`/apps/${appId}/documents`, fd, { headers: { "Content-Type": "multipart/form-data" } });
      toast.success(data.text_extraction_message || `Uploaded ${file.name}`);
      await refresh();
    } catch (err) {
      toast.error(err.response?.data?.detail || "Upload failed");
    } finally { setUploading(false); }
  };

  const deleteDoc = async (docId) => {
    if (!window.confirm("Delete this document?")) return;
    await api.delete(`/apps/${appId}/documents/${docId}`);
    toast.success("Deleted");
    await refresh();
  };

  const runQuery = async () => {
    const asked = question.trim();
    if (!asked) return;
    setRunning(true);
    setStreamStatus("Opening stream");
    setStreamSteps([{ step: "open", message: "Opening stream" }]);
    setCurrentRun({
      run_id: "streaming",
      question: asked,
      answer: "",
      citations: [],
      model_status: "streaming",
    });
    try {
      const token = localStorage.getItem("ada_token");
      const response = await fetch(`${API_BASE}/apps/${appId}/run-stream`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ question: asked }),
      });
      if (!response.ok || !response.body) {
        const { data } = await api.post(`/apps/${appId}/run`, { question: asked });
        setCurrentRun(data);
        setQuestion("");
        await refresh();
        return;
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      const handleEvent = (raw) => {
        const { event, data } = parseSseBlock(raw);
        if (!data) return;
        if (event === "status") {
          setStreamStatus(data.message || "");
          setStreamSteps((steps) => [...steps, { step: data.step || "status", message: data.message || "Working" }].slice(-5));
        }
        if (event === "citation") {
          setCurrentRun((run) => ({ ...run, citations: mergeCitations(run?.citations, [data.citation]) }));
        }
        if (event === "citations") {
          setCurrentRun((run) => ({ ...run, citations: mergeCitations(run?.citations, data.citations || []) }));
        }
        if (event === "delta") {
          setCurrentRun((run) => ({ ...run, answer: `${run?.answer || ""}${data.delta || ""}` }));
        }
        if (event === "replace") {
          setCurrentRun((run) => ({ ...run, answer: data.answer || "" }));
        }
        if (event === "done") {
          setCurrentRun(data.run);
          setStreamStatus("");
          setStreamSteps((steps) => [...steps, { step: "done", message: "Answer complete" }].slice(-5));
        }
        if (event === "error") {
          throw new Error(data.detail || "Run failed");
        }
      };

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const events = buffer.split("\n\n");
        buffer = events.pop() || "";
        for (const event of events) {
          if (event.trim()) handleEvent(event);
        }
      }
      if (buffer.trim()) handleEvent(buffer);
      setQuestion("");
      await refresh();
    } catch (err) {
      toast.error(err.response?.data?.detail || err.message || "Run failed");
    } finally {
      setRunning(false);
      setStreamStatus("");
    }
  };

  const exportSelectedAnswer = (format) => {
    if (!currentRun?.answer) {
      toast.error("Run an answer before exporting");
      return;
    }
    const payload = selectedAnswerExportPayload(appData, currentRun, docs);
    downloadStructuredExport(payload, format, `${fileSlug(appData?.name)}-selected-answer`);
  };

  const saveConfig = async () => {
    setSavingConfig(true);
    try {
      await api.put(`/apps/${appId}`, edit);
      toast.success("Saved");
      await refresh();
    } catch (err) { toast.error("Save failed"); }
    finally { setSavingConfig(false); }
  };

  const deleteApp = async () => {
    if (!window.confirm("Delete this app and all its data? This cannot be undone.")) return;
    await api.delete(`/apps/${appId}`);
    toast.success("App deleted");
    nav("/studio?tab=apps");
  };

  const runCaseLawSearch = async (e) => {
    e?.preventDefault?.();
    if (!clQuery.trim()) return;
    setClBusy(true); setClSearched(true);
    try {
      const { data } = await api.get(`/case-law/search`, { params: { q: clQuery } });
      setClResults(data.results);
    } catch (err) {
      toast.error(err.response?.data?.detail || "Search failed");
      setClResults([]);
    } finally { setClBusy(false); }
  };

  const summariseCase = async (r, idx) => {
    setSummarising(idx); setSummary(null);
    try {
      const { data } = await api.post(`/apps/${appId}/case-law/summarise`, {
        url: r.url, title: r.title, neutral_citation: r.neutral_citation,
        bailii_url: r.bailii_url, date: r.date, summary: r.summary, question: summaryFocus || null,
      });
      setSummary({ result: r, run: data });
      await refresh();
    } catch (err) {
      toast.error(err.response?.data?.detail || "Summarisation failed");
    } finally { setSummarising(null); }
  };

  if (!appData) return (
    <div className="min-h-screen bg-white"><Header />
      <div className="max-w-7xl mx-auto px-6 py-20 font-mono text-sm text-gray-500" data-testid="app-loading">Loading...</div>
    </div>
  );

  return (
    <div className="min-h-screen bg-white">
      <Header />
      <div className="max-w-7xl mx-auto px-6 py-8">
        <Link to="/studio?tab=apps" className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-ink mb-4" data-testid="back-to-studio">
          <ArrowLeft size={14} /> Studio
        </Link>

        <div className="border-b border-gray-200 pb-6 mb-6">
          <div className="font-mono text-[11px] uppercase tracking-[0.3em] text-gray-500 mb-2">{appData.app_type.replace(/_/g, ' ')}</div>
          <h1 className="font-serif text-5xl tracking-tight" data-testid="app-name">{appData.name}</h1>
          <div className="flex flex-wrap gap-6 mt-4 font-mono text-xs text-gray-600">
            <span>Jurisdiction: <span className="text-ink">{appData.jurisdiction}</span></span>
            <span>Model: <span className="text-ink">{appData.model}</span></span>
            <span>Docs: <span className="text-ink">{docs.length}</span></span>
          </div>
        </div>

          <div className="flex border-b border-gray-200 mb-6 overflow-x-auto">
          {visibleTabs.map((t) => (
            <button key={t.id} onClick={() => setTab(t.id)} className={`px-5 py-3 text-sm font-medium border-b-2 transition-colors flex items-center gap-2 ${tab === t.id ? "border-ink text-ink" : "border-transparent text-gray-500 hover:text-ink"}`} data-testid={`tab-${t.id}`}>
              <t.icon size={14} /> {t.label}
            </button>
          ))}
        </div>

        {/* PLAYGROUND */}
        {tab === "playground" && (
          <div className="grid lg:grid-cols-12 gap-0 border border-gray-200" data-testid="playground">
            {/* Left: sources list */}
            <aside className="lg:col-span-3 border-r border-gray-200 p-4 bg-gray-50">
              <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500 mb-3">Sources</div>
              {docs.length === 0 ? (
                <div className="text-sm text-gray-500">
                  {hasDocumentsFeature ? (
                    <>No documents yet. <Link to="#" onClick={(e)=>{e.preventDefault();setTab("documents");}} className="text-klein underline">Upload one</Link>.</>
                  ) : (
                    "This app was not configured with document upload."
                  )}
                </div>
              ) : (
                <ul className="space-y-2">
                  {docs.map((d) => (
                    <li key={d.doc_id} className="text-sm flex items-start gap-2 p-2 border border-gray-200 bg-white" data-testid={`source-${d.doc_id}`}>
                      <File size={14} className="mt-0.5 shrink-0 text-gray-500" />
                      <div className="overflow-hidden">
                        <div className="truncate font-medium">{d.filename}</div>
                        <div className="font-mono text-[10px] text-gray-500">{d.chunk_count} chunks</div>
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </aside>

            {/* Center: chat */}
            <div className="lg:col-span-6 flex flex-col" style={{ minHeight: "480px" }}>
              <div className="flex-1 p-6 overflow-y-auto">
                {!currentRun && !running && (
                  <div className="h-full flex items-center justify-center text-center" data-testid="playground-empty">
                    <div>
                      <div className="font-serif text-3xl mb-2">Ask a question</div>
                      <p className="text-gray-600 max-w-sm mx-auto text-sm">Ask with or without uploads. Source citations appear when indexed documents are available.</p>
                    </div>
                  </div>
                )}
                {running && (
                  <div className="mb-4 border border-klein/30 bg-klein-bg p-3" data-testid="run-loading" aria-live="polite">
                    <div className="font-mono text-[10px] uppercase tracking-widest text-klein animate-pulse">
                      {streamStatus || "Streaming answer..."}
                    </div>
                    {streamSteps.length > 0 && (
                      <div className="mt-2 flex flex-wrap gap-1.5">
                        {streamSteps.map((step, index) => (
                          <span key={`${step.step}-${index}`} className="border border-klein/20 bg-white px-2 py-1 font-mono text-[10px] text-gray-600">
                            {step.message}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                )}
                {running && !currentRun?.answer && (
                  <div className="space-y-3 mb-4" data-testid="run-token-wait">
                    <div className="h-3 w-2/3 bg-gray-100 animate-pulse" />
                    <div className="h-3 w-1/2 bg-gray-100 animate-pulse" />
                    <div className="h-3 w-3/4 bg-gray-100 animate-pulse" />
                  </div>
                )}
                {currentRun && (
                  <div className="space-y-4 animate-fade-up" data-testid="run-result">
                    <div className="border-l-2 border-klein pl-4">
                      <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500 mb-1">Question</div>
                      <div className="text-sm">{currentRun.question}</div>
                    </div>
                    <div className="prose prose-sm max-w-none">
                      <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500 mb-2">Answer</div>
                      <div className="whitespace-pre-wrap leading-relaxed text-sm">
                        {currentRun.answer ? (
                          <>
                            {renderCitations(currentRun.answer)}
                            {running && <span className="ml-0.5 animate-pulse text-klein">|</span>}
                          </>
                        ) : <span className="text-gray-500">Waiting for first tokens...</span>}
                      </div>
                    </div>
                    {currentRun.answer && (
                      <div className="border-t border-gray-200 pt-3" data-testid="selected-answer-export">
                        <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500 mb-2">Export selected answer</div>
                        <ExportButtonRow onExport={exportSelectedAnswer} disabled={running} testPrefix="answer-export" />
                      </div>
                    )}
                  </div>
                )}
              </div>
              <div className="border-t border-gray-200 p-4">
                <div className="flex gap-2">
                  <input value={question} onChange={(e)=>setQuestion(e.target.value)} onKeyDown={(e)=>e.key==="Enter" && !running && runQuery()} placeholder="Ask your AI app..." className="flex-1 border border-gray-300 px-3 py-2.5 focus:border-klein focus:outline-none text-sm" data-testid="question-input" />
                  <button onClick={runQuery} disabled={running || !question.trim()} className="bg-ink text-white px-5 py-2.5 hover:bg-klein transition-colors text-sm disabled:opacity-50 flex items-center gap-2" data-testid="run-btn">
                    {running ? "Streaming..." : <><Send size={14} /> Run</>}
                  </button>
                </div>
              </div>
            </div>

            {/* Right: citations */}
            <aside className="lg:col-span-3 border-l border-gray-200 p-4 bg-gray-50">
              <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500 mb-3">Citations</div>
              {!currentRun || (currentRun.citations || []).length === 0 ? (
                <div className="text-sm text-gray-500">
                  {running ? "Citations will appear here as sources are selected." : "Citations will appear here after a run."}
                </div>
              ) : (
                <div className="space-y-2">
                  {(currentRun.citations || []).map((c) => (
                    <button key={c.tag} onClick={() => setSelectedCitation(c)} className="w-full text-left border border-gray-200 bg-white p-3 hover:border-klein transition-colors" data-testid={`citation-card-${c.tag}`}>
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-mono text-xs text-klein">[{c.tag}]</span>
                        <span className="font-mono text-[10px] text-gray-500">{(c.score * 100).toFixed(0)}%</span>
                      </div>
                      <div className="text-xs font-medium truncate">{c.doc_name}</div>
                      <div className="text-[11px] text-gray-600 mt-1 line-clamp-3">{c.preview}</div>
                    </button>
                  ))}
                </div>
              )}
            </aside>
          </div>
        )}

        {selectedCitation && (
          <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4" onClick={()=>setSelectedCitation(null)}>
            <div className="bg-white border border-ink max-w-2xl w-full max-h-[80vh] overflow-y-auto" onClick={(e)=>e.stopPropagation()} data-testid="citation-modal">
              <div className="p-4 border-b border-gray-200 flex items-center justify-between">
                <div>
                  <div className="font-mono text-xs text-klein">[{selectedCitation.tag}]</div>
                  <div className="font-medium">{selectedCitation.doc_name}</div>
                </div>
                <button onClick={()=>setSelectedCitation(null)} className="text-sm text-gray-500 hover:text-ink" data-testid="close-citation">Close</button>
              </div>
              <div className="p-6 text-sm whitespace-pre-wrap leading-relaxed">{selectedCitation.preview}</div>
            </div>
          </div>
        )}

        {/* DOCUMENTS */}
        {tab === "documents" && (
          <div data-testid="documents-tab">
            <div className="mb-6"><Disclaimer /></div>
            <div className="border border-dashed border-gray-300 p-6 sm:p-10 text-center mb-6 hover:border-ink transition-colors">
              <input ref={fileInput} type="file" accept=".pdf,.docx,.txt,.md,.png,.jpg,.jpeg,.webp" hidden onChange={(e)=>onUpload(e.target.files?.[0])} data-testid="file-input" />
              <Upload size={32} strokeWidth={1.5} className="mx-auto mb-4 text-klein" />
              <div className="font-serif text-2xl mb-1">Upload a document</div>
              <p className="text-sm text-gray-600 mb-4">PDF, DOCX, TXT, MD or image (PNG/JPG) — up to 20MB. Originals are stored in R2; text is indexed when extraction is available.</p>
              <div className="flex flex-wrap gap-3 justify-center">
                <button onClick={()=>fileInput.current?.click()} disabled={uploading} className="bg-ink text-white px-5 py-2.5 hover:bg-klein transition-colors text-sm disabled:opacity-50" data-testid="upload-btn">
                  {uploading ? "Uploading & indexing..." : "Choose file"}
                </button>
                <CameraCapture appId={appId} onUploaded={refresh} />
              </div>
            </div>
            {docs.length === 0 ? (
              <div className="text-sm text-gray-500 font-mono">No documents yet.</div>
            ) : (
              <div className="overflow-x-auto -mx-4 sm:mx-0">
              <table className="w-full border-collapse min-w-[600px]">
                <thead>
                  <tr className="border-y border-gray-200 text-left font-mono text-[10px] uppercase tracking-widest text-gray-500">
                    <th className="py-3 px-3">Filename</th>
                    <th className="py-3 px-3">Size</th>
                    <th className="py-3 px-3">Status</th>
                    <th className="py-3 px-3">Chunks</th>
                    <th className="py-3 px-3">Uploaded</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {docs.map((d) => (
                    <tr key={d.doc_id} className="border-b border-gray-100 hover:bg-gray-50">
                      <td className="py-3 px-3 text-sm font-medium">{d.filename}</td>
                      <td className="py-3 px-3 font-mono text-xs text-gray-600">{(d.size/1024).toFixed(1)} KB</td>
                      <td className="py-3 px-3 font-mono text-[10px] text-gray-600" title={d.text_extraction_message || ""}>{d.text_extraction_status || "EXTRACTED"}</td>
                      <td className="py-3 px-3 font-mono text-xs text-gray-600">{d.chunk_count}</td>
                      <td className="py-3 px-3 font-mono text-xs text-gray-600">{new Date(d.created_at).toLocaleDateString()}</td>
                      <td className="py-3 px-3 text-right">
                        <button onClick={()=>deleteDoc(d.doc_id)} className="text-red-600 hover:text-red-800" data-testid={`delete-doc-${d.doc_id}`}><Trash2 size={14} /></button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              </div>
            )}
          </div>
        )}

        {/* CASE LAW */}
        {tab === "caselaw" && (
          <div data-testid="caselaw-tab">
            <div className="mb-4">
              <div className="font-mono text-[10px] uppercase tracking-widest text-gray-500 mb-2">// research</div>
              <h2 className="font-serif text-3xl mb-2">Search UK Case Law</h2>
              <p className="text-sm text-gray-600">Find judgments via GOV.UK Find Case Law, link through to BAILII, and generate an AI summary tailored to <span className="text-ink">{appData.name}</span>.</p>
            </div>

            <form onSubmit={runCaseLawSearch} className="flex flex-col sm:flex-row gap-2 mb-4" data-testid="caselaw-form">
              <input value={clQuery} onChange={(e)=>setClQuery(e.target.value)} placeholder='e.g. "frustration of contract" or "[2020] UKSC 19"' className="flex-1 border border-gray-300 px-3 py-2.5 focus:border-klein focus:outline-none text-sm" data-testid="caselaw-query" />
              <button type="submit" disabled={clBusy} className="bg-ink text-white px-5 py-2.5 hover:bg-klein transition-colors text-sm disabled:opacity-50 flex items-center justify-center gap-2" data-testid="caselaw-search-btn">
                <Search size={14} /> {clBusy ? "Searching..." : "Search"}
              </button>
            </form>
            <div className="mb-4">
              <label className="block text-xs font-bold uppercase tracking-wider mb-1">Optional summary focus</label>
              <input value={summaryFocus} onChange={(e)=>setSummaryFocus(e.target.value)} placeholder="e.g. How does this affect a force majeure clause?" className="w-full border border-gray-300 px-3 py-2.5 focus:border-klein focus:outline-none text-sm" data-testid="caselaw-focus" />
            </div>

            <div className="mb-6"><Disclaimer>
              <strong>Search and summary, not legal advice.</strong> Generated summaries may contain errors; verify against the full judgment and source links.
            </Disclaimer></div>

            {clBusy && <div className="font-mono text-sm text-gray-500" data-testid="cl-loading">Searching judgments...</div>}

            {!clBusy && clSearched && clResults.length === 0 && (
              <div className="border border-dashed border-gray-300 p-10 text-center" data-testid="cl-empty">
                <Scale size={32} strokeWidth={1.5} className="mx-auto mb-4 text-gray-400" />
                <div className="font-serif text-2xl mb-1">No judgments found</div>
                <p className="text-sm text-gray-600">Try a different search term.</p>
              </div>
            )}

            {!clBusy && clResults.length > 0 && (
              <div className="border border-gray-200" data-testid="cl-results">
                {clResults.map((r, i) => (
                  <article key={i} className="p-4 sm:p-5 border-b border-gray-200 last:border-b-0" data-testid={`cl-result-${i}`}>
                    <div className="flex flex-wrap items-baseline justify-between gap-2 mb-2">
                      <h3 className="font-serif text-lg sm:text-xl leading-snug">{r.title}</h3>
                      {r.date && <span className="font-mono text-[10px] uppercase tracking-widest text-gray-500">{r.date}</span>}
                    </div>
                    {r.neutral_citation && <div className="font-mono text-xs text-klein mb-2">{r.neutral_citation}</div>}
                    {r.summary && <p className="text-sm text-gray-700 leading-relaxed mb-3">{r.summary}</p>}
                    <div className="flex flex-wrap gap-3 items-center font-mono text-xs">
                      {r.url && <a href={r.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-klein hover:underline" data-testid={`cl-tna-${i}`}>Find Case Law (TNA) <ExternalLink size={11} /></a>}
                      {r.bailii_url && <a href={r.bailii_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-klein hover:underline" data-testid={`cl-bailii-${i}`}>BAILII <ExternalLink size={11} /></a>}
                      <button onClick={() => summariseCase(r, i)} disabled={summarising !== null} className="ml-auto inline-flex items-center gap-1 bg-ink text-white px-3 py-1.5 hover:bg-klein transition-colors disabled:opacity-50" data-testid={`cl-summarise-${i}`}>
                        <Sparkles size={11} /> {summarising === i ? "Summarising..." : "AI summary"}
                      </button>
                    </div>
                  </article>
                ))}
              </div>
            )}

            {summary && (
              <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-3" onClick={() => setSummary(null)}>
                <div className="bg-white border border-ink max-w-3xl w-full max-h-[85vh] overflow-y-auto" onClick={(e)=>e.stopPropagation()} data-testid="cl-summary-modal">
                  <div className="p-4 border-b border-gray-200 flex items-start justify-between gap-3">
                    <div>
                      <div className="font-mono text-[10px] uppercase tracking-widest text-klein mb-1">AI Case Summary</div>
                      <div className="font-serif text-xl leading-tight">{summary.result.title}</div>
                      {summary.result.neutral_citation && <div className="font-mono text-xs text-gray-600 mt-1">{summary.result.neutral_citation}</div>}
                    </div>
                    <button onClick={() => setSummary(null)} className="text-sm text-gray-500 hover:text-ink shrink-0" data-testid="close-cl-summary">Close</button>
                  </div>
                  <div className="p-5 text-sm whitespace-pre-wrap leading-relaxed">{summary.run.answer}</div>
                  <div className="p-4 border-t border-gray-200 bg-gray-50 font-mono text-[11px] flex flex-wrap gap-3">
                    <span className="text-gray-500">Sources:</span>
                    <a href={summary.result.url} target="_blank" rel="noreferrer" className="text-klein hover:underline inline-flex items-center gap-1">Find Case Law <ExternalLink size={10} /></a>
                    {summary.result.bailii_url && <a href={summary.result.bailii_url} target="_blank" rel="noreferrer" className="text-klein hover:underline inline-flex items-center gap-1">BAILII <ExternalLink size={10} /></a>}
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {tab === "compare" && (
          <ToolBackedFeature
            title="Compare"
            description="This app was configured with document comparison support. Use the Studio compare tool to review two versions side by side."
            to="/studio?tab=compare"
            icon={GitCompareArrows}
          />
        )}

        {tab === "brief_export" && (
          <BundleExportPanel appId={appId} appData={appData} docs={docs} currentRun={currentRun} />
        )}

        {tab === "reader" && (
          <ToolBackedFeature
            title="Guided Reader"
            description="This app was configured with the saccadic guided reader. Open it inside Studio to read dense legal text with guided focus."
            to="/studio?tab=reader"
            icon={BookOpen}
          />
        )}

        {/* CONFIG */}
        {tab === "config" && edit && (
          <div className="max-w-3xl space-y-5" data-testid="config-tab">
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider mb-2">App name</label>
              <input value={edit.name} onChange={(e)=>setEdit({...edit, name: e.target.value})} className="w-full border border-gray-300 px-3 py-2.5" data-testid="config-name" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider mb-2">Jurisdiction</label>
                <input value={edit.jurisdiction} onChange={(e)=>setEdit({...edit, jurisdiction: e.target.value})} className="w-full border border-gray-300 px-3 py-2.5" />
              </div>
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider mb-2">Model</label>
                <select value={edit.model} onChange={(e)=>setEdit({...edit, model: e.target.value})} className="w-full border border-gray-300 px-3 py-2.5 bg-white">
                  {meta.models.map((m)=><option key={m.id} value={m.id}>{m.label}</option>)}
                </select>
              </div>
            </div>
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider mb-2">System instructions</label>
              <textarea value={edit.system_instructions} onChange={(e)=>setEdit({...edit, system_instructions: e.target.value})} rows={5} className="w-full border border-gray-300 px-3 py-2.5 font-mono text-sm" />
            </div>
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider mb-2">Output format</label>
              <textarea value={edit.output_format} onChange={(e)=>setEdit({...edit, output_format: e.target.value})} rows={3} className="w-full border border-gray-300 px-3 py-2.5 font-mono text-sm" />
            </div>
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider mb-2">Safety rules</label>
              <textarea value={edit.safety_rules} onChange={(e)=>setEdit({...edit, safety_rules: e.target.value})} rows={2} className="w-full border border-gray-300 px-3 py-2.5 text-sm" />
            </div>
            <div className="flex gap-3 pt-4 border-t border-gray-200">
              <button onClick={saveConfig} disabled={savingConfig} className="bg-ink text-white px-6 py-3 hover:bg-klein transition-colors text-sm disabled:opacity-50" data-testid="save-config-btn">
                {savingConfig ? "Saving..." : "Save changes"}
              </button>
              <button onClick={deleteApp} className="border border-red-600 text-red-600 px-6 py-3 hover:bg-red-50 transition-colors text-sm ml-auto" data-testid="delete-app-btn">Delete app</button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
