import React, { useState } from "react";
import Header from "../components/Header";
import Disclaimer from "../components/Disclaimer";
import { api } from "../lib/api";
import { Search, ExternalLink, Scale, Pin } from "lucide-react";
import { toast } from "sonner";

export default function CaseLaw() {
  const [q, setQ] = useState("");
  const [busy, setBusy] = useState(false);
  const [results, setResults] = useState([]);
  const [searched, setSearched] = useState(false);
  const [aiSummaries, setAiSummaries] = useState({}); // index -> summary text or 'loading'
  const [tab, setTab] = useState("search"); // search | latest

  const fetchLatest = async () => {
    setBusy(true); setSearched(true); setAiSummaries({});
    try {
      const { data } = await api.get("/case-law/latest");
      setResults(data.results);
    } catch (err) { toast.error("Failed to load latest"); }
    finally { setBusy(false); }
  };

  const aiSummarise = async (i, r) => {
    if (aiSummaries[i]) return;
    setAiSummaries((s) => ({ ...s, [i]: "loading" }));
    try {
      const { data } = await api.post("/case-law/summarise", {
        url: r.url,
        title: r.title,
        neutral_citation: r.neutral_citation,
        bailii_url: r.bailii_url,
        date: r.date,
        summary: r.summary,
      });
      setAiSummaries((s) => ({ ...s, [i]: data.answer || data.summary }));
    } catch (err) {
      setAiSummaries((s) => ({ ...s, [i]: "Summary unavailable." }));
    }
  };

  const pin = async (r) => {
    try {
      await api.post("/pinned-cases", {
        title: r.title, url: r.url, neutral_citation: r.neutral_citation,
        bailii_url: r.bailii_url, date: r.date, summary: r.summary,
      });
      toast.success("Pinned to Drafting Tool");
    } catch (err) { toast.error("Pin failed"); }
  };

  const run = async (e) => {
    e?.preventDefault?.();
    if (!q.trim()) return;
    setBusy(true);
    setSearched(true);
    try {
      const { data } = await api.get(`/case-law/search`, { params: { q } });
      setResults(data.results);
    } catch (err) {
      toast.error(err.response?.data?.detail || "Search failed");
      setResults([]);
    } finally { setBusy(false); }
  };

  return (
    <div className="min-h-screen bg-white">
      <Header />
      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-10">
        <div className="font-mono text-[11px] uppercase tracking-[0.3em] text-gray-500 mb-2">// research</div>
        <h1 className="font-serif text-4xl sm:text-5xl tracking-tight mb-2">UK Case Law</h1>
        <p className="text-gray-600 mb-6">Search judgments from the Find Case Law service (TNA) with deep links to BAILII.</p>

        <form onSubmit={run} className="flex flex-col sm:flex-row gap-2 mb-6" data-testid="caselaw-form">
          <input
            value={q}
            onChange={(e)=>setQ(e.target.value)}
            placeholder='e.g. "Donoghue v Stevenson" or "frustration of contract"'
            className="flex-1 border border-gray-300 px-3 py-2.5 focus:border-klein focus:outline-none text-sm"
            data-testid="caselaw-query"
          />
          <button type="submit" disabled={busy} className="bg-ink text-white px-5 py-2.5 hover:bg-klein transition-colors text-sm disabled:opacity-50 flex items-center justify-center gap-2" data-testid="caselaw-search-btn">
            <Search size={14} /> {busy ? "Searching..." : "Search"}
          </button>
        </form>

        <div className="mb-6"><Disclaimer>
          <strong>Search results, not legal advice.</strong> Case summaries are generated by The National Archives' Find Case Law service. Always read the full judgment before relying on a case.
        </Disclaimer></div>

        {busy && <div className="font-mono text-sm text-gray-500" data-testid="caselaw-loading">Searching judgments...</div>}

        {!busy && searched && results.length === 0 && (
          <div className="border border-dashed border-gray-300 p-10 text-center" data-testid="caselaw-empty">
            <Scale size={32} strokeWidth={1.5} className="mx-auto mb-4 text-gray-400" />
            <div className="font-serif text-2xl mb-1">No judgments found</div>
            <p className="text-sm text-gray-600">Try a different search term or a known neutral citation like <span className="font-mono">[2020] UKSC 19</span>.</p>
          </div>
        )}

        {!busy && results.length > 0 && (
          <div className="border border-gray-200" data-testid="caselaw-results">
            {results.map((r, i) => (
              <article key={i} className="p-4 sm:p-5 border-b border-gray-200 last:border-b-0 hover:bg-gray-50" data-testid={`caselaw-result-${i}`}>
                <div className="flex flex-wrap items-baseline justify-between gap-2 mb-2">
                  <h3 className="font-serif text-lg sm:text-xl leading-snug">{r.title}</h3>
                  {r.date && <span className="font-mono text-[10px] uppercase tracking-widest text-gray-500">{r.date}</span>}
                </div>
                {r.neutral_citation && <div className="font-mono text-xs text-klein mb-2">{r.neutral_citation}</div>}
                {r.summary && <p className="text-sm text-gray-700 leading-relaxed mb-2">{r.summary}</p>}
                <div className="bg-klein-bg border-l-2 border-klein p-3 my-2 text-sm" data-testid={`ai-summary-${i}`}>
                  <span className="font-mono text-[10px] uppercase tracking-widest text-klein">AI case brief · </span>
                  {aiSummaries[i] === "loading" ? <span className="text-gray-500">Generating...</span>
                    : aiSummaries[i] ? <span className="block whitespace-pre-wrap leading-relaxed mt-2">{aiSummaries[i]}</span>
                    : <button onClick={() => aiSummarise(i, r)} className="text-klein underline">Generate full summary</button>}
                </div>
                <div className="flex flex-wrap gap-3 items-center font-mono text-xs">
                  {r.url && <a href={r.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-klein hover:underline" data-testid={`tna-link-${i}`}>TNA <ExternalLink size={11} /></a>}
                  {r.bailii_url && <a href={r.bailii_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-klein hover:underline" data-testid={`bailii-link-${i}`}>BAILII <ExternalLink size={11} /></a>}
                  <button onClick={() => pin(r)} className="ml-auto inline-flex items-center gap-1 border border-ink px-3 py-1.5 hover:bg-gray-50 transition-colors" data-testid={`pin-${i}`}>
                <Pin size={11} /> Pin to drafting
                  </button>
                </div>
              </article>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
